### ISSUE TITLE
canadian light precip METAR

### ISSUE THREAD

**Issue by Mistadouf** [vatsimnetwork/datafeed#1]
In canadian METARs − ( U+2212) is used instead of - (U+002D). That is an issue for multiple programs using vatsim's METAR feed. (ie. vATIS, Euroscope)

I'm posting here as it seems the best place to do so. Can something be done on Vatsim's side or should the issue be communicated to each app developer separately?

**Comment by williammck** [comment]
Thanks for the report! We'll get that fixed.
(This repo wasn't necessarily the right place, but the repo for METARs is currently private, so I don't blame you 😆)

**Comment by Mistadouf** [comment]
thanks for the quick reply. I have another thing to add. The space between 1 and 3/4 in the following metar seems different as it also causes an issue with vATIS and Euroscope:

CYUL 092300Z VRB21G41KT 1 3/4SM R24R/5500VP6000FT/D +RA BR OVC007 21/20 A2950 RMK RA2ST6 SLP992 DENSITY ALT 1300FT

It seems to be only the space in the visibility part of the metar, the rest seems fine.

**Comment by Mistadouf** [comment]
![image](https://github.com/user-attachments/assets/d7517753-1b72-4073-a7ea-ffbbb3d14f2f)
here's the result in Euroscope

**Comment by williammck** [comment]
Thanks for that as well, will have the fix rolling out shortly.
